config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  get 'posts/index'
  get 'posts/new' => 'posts#new'
  devise_for :users
  get 'home/index'
  get 'home/show'
  post 'posts'  =>  'posts#create'
  resources :users, only: [:show]
  resources :posts, only: [:index, :show, :create] do
    resources :answers, only: [:create]
  end
  get 'users/sign_out' => 'users#sign_out'
  root to: "posts#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :answers
  mount_uploader :image, ImageUploader
  validates :theme, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :answers
  validates :username, presence: true, length: { maximum: 6 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = Answer.new(answer_params)
    @answer.user_id = current_user.id
    @answer.save
    if @answer.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end

  end

  private
  def answer_params
    params.permit(:answer, :post_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :username, :email, :password, :password_confirmation　]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = Post.all.page(params[:page]).order(id: :desc).per(5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(image: post_params[:image], theme: post_params[:theme], user_id: current_user.id)
    if !(@post.save)
      redirect_to posts_new_path
    else
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
    @answers = Answer.where(post_id: @post.id).order(id: :desc)
    @answer = Answer.new
  end

  private
  def post_params
    params.require(:post).permit(:image, :theme)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @users_theme = Post.where(user_id: @user.id).order(id: :desc).limit(3)
    @users_answer = Answer.where(user_id: @user.id).order(id: :desc).limit(3)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yy0916Bokete</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Microposts</title>
    <%= csrf_meta_tags %>

    <!-- コード追加　Bootstrap CSS読み込みコード-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- コード追加　Bootstrap JavaScript読み込みコード-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.haml
.contents.row
  .success
    %h3
      投稿が完了しました。
    %a.btn{:href => "/",class: "move_top_btn"} 投稿一覧へ戻る

app/views/posts/index.html.haml
.header
  .header_logo
    Make Me Laugh!
  .username
    %span ニックネーム:
  %button{"data-modal": "delete-item", "data-open": "modal", class: "header_user_btn"}
    = link_to current_user.username, user_path(current_user), class: "header_user_name"
  %button{"data-modal": "delete-item", "data-open": "modal", class: "post_theme"}
    = link_to 'お題を投稿', posts_new_path, class: "post_theme_btn"
%main.main_boke_contant
%h1.post_all 投稿一覧
%ul
  - @posts.each do |posts|
    .boke_box
      .box_user_name
        投稿者: 
        = User.find(posts.user_id).username
      .box_theme
        お題: 
        = posts.theme
      .boke_image
        = image_tag posts.image.to_s
    .answer_box
      みんなの回答
      -num = 0
      - Answer.where(post_id: posts).order(id: :desc).each do |kaitou|
        .answer-small-box
          .answer_user_name
            = kaitou.user.username
            .answer-body
              .answer_text
                = kaitou.answer
            %hr/
        -num += 1
        -break if num== 3
    .answer_create_btn
      = link_to 'このお題に答える', post_path(posts)
    .other_find
      = link_to 'もっと見る', post_path(posts)
.pagenate
  = paginate @posts

app/views/posts/new.html.haml
.contents.row
  .container
    = form_for @post do |f|
      %h3
        投稿内容
      %span 画像
      = f.label :image, :name => "image", :autofocus => "true"
      = f.file_field :image, :class => "image_form"
      %span お題
      = f.text_field :theme, :class => "text_area",:placeholder => "お題を入力", :rows => "10"
      %input{:type => "submit", :value => "投稿する", :class => "post_btn"}/

app/views/posts/show.html.haml
.boke_box
  .box_user_name
    投稿者:
    = @user.username
  .box_theme
    お題: 
    = @post.theme
  .boke_image
    = image_tag @post.image.to_s
.answer_box_show
  みんなの回答
  - @answers.each do |kaitou|
    .answer-small-box
      .answer_user_name
        = kaitou.user.username
        .answer-body
          .answer_text
            = kaitou.answer
        %hr/
  = form_for [@post, @answer] do |f|
    %textarea{:name => "answer", :placeholder => "text", :rows => "10", :class => "post_text_area", :required => true}
    %input{:type => "submit", :value => "回答する", :class => "answer_post_btn"}/

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name),class: "user_create_link" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "ユーザー登録", new_registration_path(resource_name),class: "user_create_link" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れてしまった場合", new_password_path(resource_name),class: "user_create_link" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.haml
.header
  .header_logo
    Make Me Laugh!
  %button{"data-modal": "delete-item", "data-open": "modal", class: "log_out"}
    = link_to "ログアウト", users_sign_out_path, method: :delete, class: "log_out_btn"
  %button{"data-modal": "delete-item", "data-open": "modal", class: "post_theme"}
    = link_to 'お題を投稿', posts_new_path, class: "post_theme_btn"
.user_create_theme
  .user_create_theme_all
    -if current_user.id == @user.id
      あなたのお題
    -else
      = @user.username
      さんの最新のお題
  - @users_theme.each do |users|
    .boke_box
      .box_theme
        お題: 
        = users.theme
      .boke_image
        = image_tag users.image.to_s
    .answer_box
      みんなの回答
      - Answer.where(post_id: users.id).order(id: :desc).limit(3).each do |kaitou|
        .answer-small-box
          .answer_user_name
            = kaitou.user.username
            .answer-body
              .answer_text
                = kaitou.answer
            %hr/
    .other_find_userpage
      = link_to 'もっと見る', post_path(users)
.user_answer
  .user_create_theme_all
    -if current_user.id == @user.id
      あなたが回答したお題
    -else
      = @user.username
      さんが最近回答したお題
  - @users_answer.each do |post_answer|
    - Post.where(id: post_answer.post_id).each do |users|
      .boke_box
        .box_theme
          お題: 
          = users.theme
        .boke_image
          = image_tag users.image.to_s
      .answer_box
        .answer-small-box
          .answer_user_name
            = @user.username
            .answer-body
              .answer_text
                = post_answer.answer
            %hr/
      .other_find_userpage2
        = link_to '他の人の回答を見る', post_path(users)